-- 한국 은행
CREATE SEQUENCE KOREA_BANK_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE KOREA_BANK (
    id BIGINT PRIMARY KEY DEFAULT nextval('KOREA_BANK_SEQ'),
    base_interest_rate NUMERIC(2,2), -- 소수점 앞 , 뒤 몇개
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 은행 상품
CREATE SEQUENCE BANK_PRODUCT_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE BANK_PRODUCT (
    id BIGINT PRIMARY KEY DEFAULT nextval('BANK_PRODUCT_SEQ'),
    name VARCHAR(255),
    type CHECK (type IN ('DEPOSIT', 'SAVINGS')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--