-- Stock
CREATE SEQUENCE STOCK_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE STOCK (
    id BIGINT PRIMARY KEY DEFAULT nextval('STOCK_SEQ'),
    name VARCHAR(255) NOT NULL UNIQUE,
    current_price INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE
);

-- Stock 가격 변동 내역
CREATE SEQUENCE STOCK_PRICE_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE STOCK_PRICE (
    id BIGINT PRIMARY KEY DEFAULT nextval('STOCK_PRICE_SEQ'),
    stock_id BIGINT NOT NULL,
    price INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Stock 관련 뉴스
CREATE SEQUENCE STOCK_NEWS_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE STOCK_NEWS (
    id BIGINT PRIMARY KEY DEFAULT nextval('STOCK_NEWS_SEQ'),
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    is_good_news CHECK (is_good_news IN ('GOOD', 'NORMAL', 'BAD'))
);

-- Stock 주문 내역
CREATE SEQUENCE STOCK_ORDER_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE STOCK_ORDER (
    id BIGINT PRIMARY KEY DEFAULT nextval('STOCK_ORDER_SEQ'),
    stock_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    price INTEGER NOT NULL,
    total_price INTEGER NOT NULL,
    is_sell BOOLEAN NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

