-- World
CREATE SEQUENCE WORLD_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE WORLD (
    id BIGINT PRIMARY KEY DEFAULT nextval('WORLD_SEQ'),
    name VARCHAR(50) NOT NULL,
    owner_id BIGINT NOT NULL,
    member_cnt INTEGER NOT NULL,
    max_member_cnt INTEGER,
    code VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);


CREATE SEQUENCE WORLD_MEMBER_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE WORLD_MEMBER (
    id BIGINT PRIMARY KEY DEFAULT nextval('WORLD_MEMBER_SEQ'),
    word_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL
);